version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "beehive-recorder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16i8bacyil4zm"
s3_prefix = "beehive-recorder"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
